### ISSUE TITLE
Agree on how to define/identify "Major Hospitals"

### ISSUE THREAD

**Issue by MWeissSharp** [nss-data-science-cohort-6/hop_team-floatingspirit#4]
The classification "General Acute Care Hospitals" included Critical Access Hospitals and Children's Hospitals

The grouping "Hospitals" includes all of the above plus Psychiatric and Rehabilitation Hospitals

**Comment by jmayf123** [comment]
Using only Display Name  = 'General Acute Care Hospitals'
